### ISSUE TITLE
Resynthesis of Original Hit

### ISSUE THREAD

**Issue by mattodd** [StructuralGenomicsConsortium/CNP7-RdRp-S1-Tetrazole#1]
The [original hit](https://github.com/StructuralGenomicsConsortium/CNP7-RdRp-S1-Tetrazole/wiki/Origins-of-this-Project) (RA-0010017-01) molecule needs resynthesis.

The current plan is as follows

![Hit target synthetic scheme](https://github.com/StructuralGenomicsConsortium/CNP7-RdRp-S1-Tetrazole/assets/133207721/49e6efc5-1c11-4669-91a8-ba7788d9a6cb)

**Comment by HadiaAmahli** [comment]
We are interested in exploring the potency of the [original hit RA-0010017-01](https://github.com/StructuralGenomicsConsortium/CNP7-RdRp-S1-Tetrazole/wiki/Origins-of-this-Project) analogues to study the SAR which will help to make a potent drug-like molecule. Here are the commercially available analogues:
![1](https://github.com/StructuralGenomicsConsortium/CNP7-RdRp-S1-Tetrazole/assets/133207721/3911b1c0-5287-4df6-b686-51a49cbb47d2)
We are interested in the SAR study of the carboxylic acid isosteres of tetrazol as well, however these analogues are not commercially available (see below):
![2](https://github.com/StructuralGenomicsConsortium/CNP7-RdRp-S1-Tetrazole/assets/133207721/6041dc14-4e22-4574-9089-fe935ddfa378)

**Comment by mattodd** [comment]
Hi @HadiaAmahli - for the commercially-available ones, those seem good. Keep us posted if the order goes in (actually I wonder if we should move that to a new Issue (number 2), since this is about resynthesis of the original hit, rather than simple commercially-available analogues of the original hit). For the ones in the lower panel, I don't know. Some of those linker variants are pretty funky. I think the carboxylic acid idea was just to replace the terminal tetrazole (which is a common isostere of a carboxylic acid) so that compound should be a target for sure. As I think @tmw20653 mentioned somewhere - easy from the mono-ester of terephthalic acid?

**Comment by HadiaAmahli** [comment]
@mattodd  I am dealing with two suppliers to order the commercial analogues as they are not listed in the UCL-iprocurment system, the purchase of 6 analogues will be proceeded shortly from Enamine, the 14 remaining analogues are available in Aurora Fine Chemicals but they look so expensive that's why I'm trying to find alternative suppliers/analogues.
It's a good idea to create another issue for the commercially available analogue. I'll do so.
Regarding the tetrazole replaced by carboxylic acid: yes agreed, I will make this analogue starting from the ethyl ester of terephthalic acid, the chemicals have been ordered and to be arrived by the end of this week.
Regarding the unavailable carboxilic acid isosteres: I suggest it is a good idea to think about these compounds to produce changes in the physicochemical properties or susceptibility to metabolism compared to the parent compound in order to lead to improved derivatives and allows us to have better SPR and SAR studies. Unfortunately they are unavailable but I can make some if necessary.
The following paper shows an assessment of the relative differences in physicochemical properties of carboxylic acid isosteres, compared to the corresponding carboxylic acid.
Structure Property Relationships of Carboxylic Acid Isosteres. J. Med. Chem. 2016, 59, 3183−3203, DOI: 10.1021/acs.jmedchem.5b01963

**Comment by HadiaAmahli** [comment]
The [original hit](https://github.com/StructuralGenomicsConsortium/CNP7-RdRp-S1-Tetrazole/wiki/Origins-of-this-Project) (RA-0010017-01) molecule has been synthesised by the following route and obtained as a white powder with 87% yield, this re-synthetic molecule will be shipped to the UNC to be tested vs SARS-Cov2 RdRp.
![Github3](https://github.com/StructuralGenomicsConsortium/CNP7-RdRp-S1-Tetrazole/assets/133207721/d6ffa4a4-a490-49e0-942b-e385fa38d44f)

**Comment by HadiaAmahli** [comment]
Since Tetrazoles are amongst the most commonly employed carboxylic acid isosteres, we decided to re-synthesize the isostere of The [original hit](https://github.com/StructuralGenomicsConsortium/CNP7-RdRp-S1-Tetrazole/wiki/Origins-of-this-Project) (RA-0010017-01) as I mentioned in a previous comment to test its antiviral activity and compare it with The [original hit](https://github.com/StructuralGenomicsConsortium/CNP7-RdRp-S1-Tetrazole/wiki/Origins-of-this-Project) (RA-0010017-01) antiviral activity.
The corresponding isostere analogue has been synthesized  as follows and obtained as a white powder with 92% yield over two steps and to be shipped to the UNC for testing.
![Github4](https://github.com/StructuralGenomicsConsortium/CNP7-RdRp-S1-Tetrazole/assets/133207721/023ce141-7da4-4e02-a921-79bd1555ccad)

**Comment by HadiaAmahli** [comment]
Non of the synthesized or purchased analogues showed improved solubility or activity that's why we end this series.
